# Generated by Django 4.0.4 on 2022-05-10 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershop',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rgr.city'),
        ),
    ]
