# Generated by Django 4.0.4 on 2022-05-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgr', '0002_alter_barbershop_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='barbershop',
            table='Barbershop',
        ),
        migrations.AlterModelTable(
            name='city',
            table='City',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
        migrations.AlterModelTable(
            name='employees',
            table='Employees',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
        migrations.AlterModelTable(
            name='services',
            table='Services',
        ),
    ]
