# Generated by Django 4.0.4 on 2022-05-11 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rgr', '0004_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rgr.employees'),
        ),
        migrations.AlterField(
            model_name='order',
            name='barbershop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rgr.barbershop'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rgr.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rgr.services'),
        ),
    ]
